carts/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_goods/$', views.add_goods, name='add_goods'),
]

goods/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list/$', views.g_list, name='list'),
    url(r'^detail/$', views.detail, name='detail'),
    url(r'^contact/$', views.contact_message, name='contact'),
]

huanjiangpu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^$', include('goods.urls', namespace='goods')),
    url(r'^admin/', admin.site.urls),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^order/', include('order.urls', namespace='order')),

]

users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^address/$', views.address, name='address'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^login_handle/$', views.login_handle, name='login_handle'),
]

goods/models.py
from db.AbstractModel import BaseModel
from django.db import models


class Category(BaseModel):
    cate_name = models.CharField(max_length=20)
    cate_desc = models.CharField(max_length=500)

    def __str__(self):
        return self.cate_name


class GoodsManager(models.Manager):
    def goods_by_hot(self):
        return self.all().order_by('g_look')[:10]

    def goods_by_cate(self, cate_id):
        return self.filter(g_cate_id=cate_id)

    def goods_by_id(self, goods_id):
        try:
            return self.get(pk=goods_id)
        except Goods.DoesNotExist:
            return None
        except Exception as e:
            print(e)
            return None


class Goods(BaseModel):
    # 名字，
    g_name = models.CharField(max_length=30)
    # 类别，
    g_cate = models.ForeignKey(Category)
    # 主图，
    g_image = models.ImageField()
    # 描述，
    g_desc = models.CharField(max_length=100)
    # 单位，
    g_unit = models.CharField(max_length=10)
    # 价格，
    g_price = models.DecimalField(max_digits=10, decimal_places=2)
    # 人气，
    g_look = models.IntegerField(default=0)

    objects = GoodsManager()

    def __str__(self):
        return self.g_name


class Activity(BaseModel):
    # 是否活动中
    act_activiting = models.BooleanField(default=False)
    # 标题
    act_title = models.CharField(max_length=50)
    # 副标题
    act_subtitle = models.CharField(max_length=200)
    # 详情
    act_detail = models.CharField(max_length=500)
    # 图（1413*900）
    act_image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.act_title


class Announcement(BaseModel):
    # 公告标题
    anno_title = models.CharField(max_length=15)
    # 公告详情
    anno_detail = models.CharField(max_length=200)
    # 主图，
    anno_image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.anno_title

goods/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import *
from users.models import *
from utils.wrapper import *


def index(request):
    # 公告
    anno = Announcement.objects.all().order_by('-id')[:1].first()

    # 活动
    acti = Activity.objects.filter(act_activiting=True).order_by('-create_time')[:1].first()

    # 类别
    cate_list = Category.objects.all()

    # 人气商品
    # hot_list = Goods.objects.goods_by_hot()

    return render(request, 'goods/goods_index.html', locals())


def g_list(request):
    cate_id = get(request, 'id')
    try:
        cate_obj = Category.objects.get(id=cate_id)
    except Category.DoesNotExist:
        cate_obj = Category.objects.all().first()

    # 类别商品
    goods_list = Goods.objects.goods_by_cate(cate_id)

    return render(request, 'goods/goods_list.html', locals())


# 商品详情
def detail(request):
    goods_id = get(request, 'id')

    # 人气商品
    goods = Goods.objects.goods_by_id(goods_id)
    response = render(request, 'goods/goods_detail.html', locals())
    set_cookie(response, 'user', 'panjuanjuan')
    return response


# 投诉意见
def contact_message(request):
    ret = 0
    if check_contact_pramas(request):
        # 写入数据库
        save_contact_message(request)
        ret = 1

    return JsonResponse({"ret": ret})


def check_contact_pramas(request):
    c_name = post(request, 'c_name')
    if not c_name:
        return False

    c_email = post(request, 'c_tel')
    if 11 != len(c_email):
        return False

    c_message = post(request, 'c_message')
    if not c_message:
        return False

    return True


def save_contact_message(request):
    con = Contact()
    con.c_uname = post(request, 'c_name')
    con.c_tel = post(request, 'c_tel')
    con.c_message = post(request, 'c_message')
    con.save()

templates/goods/goods_detail.html
{% extends 'common/base.html' %}

{% load staticfiles %}

{% block title %}
    <title>花匠铺-详情</title>
{% endblock title %}

{% block body %}

<!-- Page Wrapper -->
<div id="page-wrapper">

    <!-- Wrapper -->
    <div id="wrapper">

    <!-- Panel (Banner) -->
        <section class="panel banner right">
            <div class="content color0 span-2-75">
                <input type="hidden" id="goods_id" value="{{ goods.id }}" />
                <h1>{{ goods.g_name }}<br /></h1>
                <h3 id="price">{{ goods.g_unit }} / ¥ <em>{{ goods.g_price }}</em></h3>
                <div class="goods_num clearfix">
                    <input type="text" id="buy_num" value="1">
                    <div id="total">总价：<em>{{ goods.g_price }}</em>元</div><br>
                    <input type="hidden" id="goods_id">
                    {% csrf_token %}
                    <a href="javascript:;" class="button special color2" id="add_cart">加入购物车</a>
                    <a href="{% url 'users:login' %}" class="button special color2" id="login">登录</a>
                </div>

            </div>
            <div class="image filtered span-2-75" data-position="25% 25%">
                <img src="{% static goods.g_image %}"/>
            </div>
        </section>

    <!-- Panel (Spotlight) -->
        <section class="panel spotlight large left">
            <div class="content span-5">
                <h2 class="major">{{ goods.g_name }}</h2>
                <p>花语：{{ goods.g_florid }}</p>
            </div>
            <div class="image filtered tinted" data-position="top right">
                <img src="{% static goods.g_image %}" />
            </div>
        </section>


    <!-- Panel -->
        <section class="panel color4-alt">
            <div class="intro color4">
                <h2 class="major">联系我们</h2>
                <p>您的每一个意见，小花匠都愿意倾听。您的每一个微笑，都是小花匠坚持的动力！<br>让我们一起装点生活，欢迎您联系我们！</p>
            </div>
            <div class="inner columns divided">
                <div class="span-3-25">
                    <form method="post" action="#">
                        <div class="field half">
                            <label for="name">您的名字</label>
                            <input type="text" name="name" id="name" />
                        </div>
                        <div class="field half">
                            <label for="email">您的邮箱</label>
                            <input type="email" name="email" id="email" />
                        </div>
                        <div class="field">
                            <label for="message">您想说的话</label>
                            <textarea name="message" id="message" rows="4"></textarea>
                        </div>
                        <ul class="actions">
                            <li><input type="submit" value="发送" class="button special" /></li>
                        </ul>
                    </form>
                </div>
                <div class="span-1-5">

                    <ul class="contact-icons color1">
                        <h3 class="major">微信号</h3>
                        <img style="height: 300px; width: 230px" src="/static/images/wx.jpg"/>
                    </ul>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock body %}

{% block footer_js %}

    <script>
    $(function () {
        $('#login').hide();
       $('#buy_num').change(function () {
           var $num = parseInt($('#buy_num').val());
           if (!($num > 1)){
               $num = 1
           }
           var $price = parseFloat($('#price em').html());
           var $total = $num * $price;
           $("#total em").html($total);
       });

       $('#add_cart').click(function () {
           var $csrf_value = $('input[name="csrfmiddlewaretoken"]').val();
           $.post('{% url "carts:add_goods" %}',
               {'csrfmiddlewaretoken': $csrf_value,'goods_id':$('#goods_id').val(), 'goods_num': $('#buy_num').val()},
               function(data){
                if (data.ret == 0){
                    alert("请先登录")
                    $('#login').show();
                }
                if (data.ret == 1){
                    alert("添加成功")
                }
           });
       });
    });
    </script>

{% endblock footer_js %}


templates/goods/goods_index.html
{% extends 'common/base.html' %}

{% load staticfiles %}
{% load cate_filter %}

{% block body %}
		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Wrapper -->
					<div id="wrapper">

						<!-- 公告 -->
							<section class="panel banner right">
								<div class="content color0 span-3-75">
									<h2 class="major">{{ anno.anno_title }}</h2>
									<p>{{ anno.anno_detail }}</p>
									<ul class="actions">
                                        {% if not request.COOKIES.userid %}
										<li><a href="{% url 'users:login' %}" class="button">登录</a></li>
                                        {% endif %}
									</ul>
								</div>
								<div class="image filtered span-1-75" data-position="25% 25%">
									<img src="{% static anno.anno_image %}" alt="{{ anno.anno_title }}" />
								</div>
							</section>

						<!-- 活动 -->
							<section class="panel spotlight medium right" id="first">
								<div class="content span-7">
									<h2 class="major">{{ acti.act_title }}</h2>
									<p>{{ acti.act_subtitle }}</p>
									<p>{{ acti.act_detail }}</p>
								</div>
								<div class="image filtered tinted" data-position="top left">
									<img src="{% static acti.act_image %}" alt="{{ acti.act_title }}" />
								</div>
							</section>

                        <!-- 类别 -->

							<section class="medium category image" style="width: {{ cate_list.count | cate_width }}px">
                                <ul>
                                    {% for cata in cate_list %}
                                    <li style="left: {{ forloop.counter | cate_left }}px">
                                        <span>{{ cata.cate_name }}</span>
                                        <a href="{% url 'goods:list' %}?id={{ cata.id }}"><img src="{% static acti.act_image %}"/></a>
                                    </li>
                                    {% endfor %}
                                </ul>
							</section>


						<!-- 联系我们 -->
							<section class="panel color4-alt">
								<div class="intro color4">
									<h2 class="major">联系我们</h2>
									<p>您的每一个意见，小花匠都愿意倾听。您的每一个微笑，都是小花匠坚持的动力！<br>让我们一起装点生活，欢迎您联系我们！</p>
								</div>
								<div class="inner columns divided">
									<div class="span-3-25">
										<form method="post" action="javascript:;" id="contact_form">
                                            {% csrf_token %}
											<div class="field half">
												<label for="name">您的名字</label>
												<input type="text" id="name"/>
											</div>
											<div class="field half">
												<label for="tel">您的电话</label>
												<input type="tel" id="tel"/>
											</div>
											<div class="field">
												<label for="message">您想说的话</label>
												<textarea id="message" rows="4"></textarea>
											</div>
											<ul class="actions">
												<li><input type="submit" value="发送" class="button special" /></li>
											</ul>
										</form>
									</div>
									<div class="span-1-5">

										<ul class="contact-icons color1">
                                            <h3 class="major">微信号</h3>
                                            <img style="height: 300px; width: 230px" src="/static/images/wx.jpg"/>
										</ul>
									</div>
								</div>
							</section>
					</div>
			</div>

{% endblock body %}

{% block footer_js %}
    <script src="{% static 'js/addtion.js' %}"></script>
    <script>
    $(function () {
        $('#contact_form').submit(function () {
            var $c_name = $('#name').val();
            var $c_tel = $('#tel').val();
            var $c_message = $('#message').val();
            var $csrf_value = $('input[name="csrfmiddlewaretoken"]').val()
            $.post(
                "{% url 'goods:contact' %}",
                {'c_name': $c_name, 'c_tel': $c_tel, 'c_message': $c_message, 'csrfmiddlewaretoken': $csrf_value},
                function (data) {
                if (data.ret == 1){
                    alert("谢谢您的反馈！")
                    $('#name').val("");
                    $('#tel').val("");
                    $('#message').val("");
                }
                else {
                    alert("对不起，请稍后再试！")
                }
            })
        });
    });

    </script>
{% endblock footer_js %}

templates/goods/goods_list.html
{% extends 'common/base.html' %}

{% load staticfiles %}

{% block title %}
    <title>花匠铺-列表</title>
{% endblock %}

{% block body %}
		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Wrapper -->
					<div id="wrapper">

						<!-- Panel -->
							<section class="panel">
								<div class="intro color2">
									<h2 class="major">{{ cate_obj.cate_name }}</h2>
									<p>{{ cate_obj.cate_desc }}</p>
								</div>
								<div class="gallery">
                                    {% for goods in goods_list %}
									<a href="{% url 'goods:detail' %}?id={{ goods.id }}" class="image filtered span-2-5" data-position="top"><img src="{% static goods.g_image %}" alt="{{ goods.g_name }}" /></a>
                                    {% endfor %}
                                </div>
							</section>

						<!-- Panel -->
							<section class="panel color4-alt">
								<div class="intro color4">
									<h2 class="major">联系我们</h2>
									<p>您的每一个意见，小花匠都愿意倾听。您的每一个微笑，都是小花匠坚持的动力！<br>让我们一起装点生活，欢迎您联系我们！</p>
								</div>
								<div class="inner columns divided">
									<div class="span-3-25">
										<form method="post" action="#">
											<div class="field half">
												<label for="name">您的名字</label>
												<input type="text" name="name" id="name" />
											</div>
											<div class="field half">
												<label for="email">您的邮箱</label>
												<input type="email" name="email" id="email" />
											</div>
											<div class="field">
												<label for="message">您想说的话</label>
												<textarea name="message" id="message" rows="4"></textarea>
											</div>
											<ul class="actions">
												<li><input type="submit" value="发送" class="button special" /></li>
											</ul>
										</form>
									</div>
									<div class="span-1-5">

										<ul class="contact-icons color1">
                                            <h3 class="major">微信号</h3>
                                            <img style="height: 300px; width: 230px" src="/static/images/wx.jpg"/>
										</ul>
									</div>
								</div>
							</section>

					</div>

			</div>
{% endblock body %}