carts/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_goods/$', views.add_goods, name='add_goods'),
]

huanjiangpu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^$', include('goods.urls', namespace='goods')),
    url(r'^admin/', admin.site.urls),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^order/', include('order.urls', namespace='order')),

]

users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^address/$', views.address, name='address'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^login_handle/$', views.login_handle, name='login_handle'),
]

users/models.py
from django.db import models
from db.AbstractModel import *
from utils.wrapper import *

# Create your models here.


class UserManager(models.Manager):

    def user_register(self, request):
        user = User()
        user.u_name = post(request, 'u_name')
        user.u_tele = post(request, 'u_phone')
        user.u_pass = password_encryption(post(request, 'u_pass'))
        user.save()

    def user_update_recv(self, request):
        pass

    def user_by_name(self, u_name):
        try:
            return self.get(u_name=u_name)
        except User.DoesNotExist:
            return None


class User(BaseModel):
    u_name = models.CharField(max_length=20)
    u_pass = models.CharField(max_length=80)
    u_tele = models.CharField(max_length=11)
    u_recv = models.CharField(max_length=20)
    u_addr = models.CharField(max_length=50)
    u_recv_tele = models.CharField(max_length=11)

    objects = UserManager()


class Contact(BaseModel):
    c_uname = models.CharField(max_length=20)
    c_tel = models.CharField(max_length=20)
    c_message = models.CharField(max_length=20)

users/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .models import *


def index(request):
    return render(request, 'users/user_order.html', locals())


def register(request):
    return render(request, 'users/user_register.html', locals())


def login(request):
    return render(request, 'users/user_login.html', locals())


def address(request):
    return render(request, 'users/user_address.html', locals())


# 注册逻辑
def register_handle(request):

    if check_register_params(request):
        # 数据入库
        User.objects.user_register(request)
        return redirect(reverse('users:login'))
    else:
        return redirect(reverse('users:register'))


# 登录逻辑
def login_handle(request):
    if check_login_params(request):
        response = redirect(reverse('goods:index'))
        keep_user_online(request, response)
        return response
    else:
        return redirect(reverse('users:login'))


def check_register_params(request):
    u_name = post(request, 'u_name')
    if not 5 <= len(u_name) <= 20:
        return False

    u_phone = post(request, 'u_phone')
    if not 11 == len(u_phone):
        return False

    u_pass = post(request, 'u_pass')
    if not 8 <= len(u_pass) <= 20:
        return False

    u_repass = post(request, 'u_repass')
    if not u_pass == u_repass:
        return False

    user = User.objects.user_by_name(u_name)
    if user:
        return False

    return True


def check_login_params(request):
    u_name = post(request, 'u_name')
    if not 5 <= len(u_name) <= 20:
        return False

    u_pass = post(request, 'u_pass')
    if not 8 <= len(u_pass) <= 20:
        return False

    user = User.objects.user_by_name(u_name)
    if not user:
        return False

    if not user.u_pass == password_encryption(u_pass):
        return False

    return True


def keep_user_online(request, response):
    u_name = post(request, 'u_name')
    user = User.objects.user_by_name(u_name)
    set_cookie(response, str(user.id), 'u_id')

templates/users/user_address.html
{% extends 'common/base.html' %}

{% load staticfiles %}

{% block title %}
	<title>花匠铺-用户地址</title>
{% endblock %}

{% block body %}

	<!-- Page Wrapper -->
	<div id="page-wrapper">

		<!-- Wrapper -->
		<div id="wrapper">

			<!-- Panel (Banner) -->
			<section class="panel banner right">
				<div class="content color0 span-2-75">
					<h1 class="major">欢迎回来！
						<br /> 张三丰
					</h1>
					<p>今天你的幸运花是
						<strong>紫罗兰</strong>,代表永恒的美丽
						<br>
						<a href="#" target="_blank" title="查看订单">查看订单</a>
						<br>
						<a href="#" target="_blank" title="修改地址">修改地址</a>
					</p>
				</div>
				<div class="image filtered span-2-75" data-position="25% 25%">
					<img src="images/user.jpg" alt="" />
				</div>
			</section>

			<!-- Panel -->
			<section class="panel color1-alt">
				<div class="intro color1">
					<h2 class="major">地址 》》</h2>
					<p> 感恩，
						<br> 使我们的生命更加灿烂。投之以桃，报之以李，
						<br> 感恩，让生活充满人性，充满和谐。
					</p>
				</div>
				<div class="inner columns aligned">
					<div class="span-3">
						<h3 class="major">默认地址</h3>
						<h4>上海市</h4>
						<div class="table-wrapper">
							<table>
								<!-- <thead>
									<tr>
										<th colspan="4">名称</th>
									</tr>
								</thead> -->
								<tbody>
									<tr>
										<td>收件人</td>
										<td colspan="3">张三丰</td>
									</tr>
									<tr>
										<td>联系电话</td>
										<td>13044998888</td>
									</tr>
									<tr>
										<td>所在城市</td>
										<td colspan="3">上海市 浦东新区 万香科技园7517</td>
									</tr>

								</tbody>
								<tfoot>
									<tr>
										<td>
											<a href="#" class="button">修改地址</a>
										</td>
										<td colspan="3">
									</tr>
								</tfoot>
							</table>
						</div>
					</div>
				</div>
			</section>

			<!-- Panel -->
			<section class="panel color1-alt">
				<div class="inner columns aligned">
					<div class="span-3">
						<h3 class="major">地址</h3>
						<h4>上海市</h4>
						<div class="table-wrapper">
							<table>
								<tbody>
									<tr>
										<td>收件人</td>
										<td colspan="3">张三丰</td>
									</tr>
									<tr>
										<td>联系电话</td>
										<td>13044998888</td>
									</tr>
									<tr>
										<td>所在城市</td>
										<td colspan="3">上海市 浦东新区 万香科技园7517</td>
									</tr>

								</tbody>
								<tfoot>
									<tr>
										<td>
											<a href="#" class="button">修改地址</a>
										</td>
										<td colspan="3">
									</tr>
								</tfoot>
							</table>
						</div>
					</div>
				</div>
			</section>Í

			<!-- Panel -->
			<section class="panel">
				<div class="intro color2">
					<h2 class="major">人气商品</h2>
					<p> 看不清楚前面的道路，挽留不住岁月的脚步，还好有你的呵护，能听我把苦乐倾诉。感谢你，我的朋友，真心愿你好运一路，快乐常驻，把幸福一直留住。</p>
				</div>
				<div class="gallery">
					<div class="group span-3">
						<a href="images/gallery/fulls/01.jpg" class="image filtered span-3" data-position="bottom">
							<img src="images/gallery/thumbs/01.jpg" alt="" />
						</a>
						<a href="images/gallery/fulls/02.jpg" class="image filtered span-1-5" data-position="center">
							<img src="images/gallery/thumbs/02.jpg" alt="" />
						</a>
						<a href="images/gallery/fulls/03.jpg" class="image filtered span-1-5" data-position="bottom">
							<img src="images/gallery/thumbs/03.jpg" alt="" />
						</a>
					</div>
					<a href="images/gallery/fulls/04.jpg" class="image filtered span-2-5" data-position="top">
						<img src="images/gallery/thumbs/04.jpg" alt="" />
					</a>
					<div class="group span-4-5">
						<a href="images/gallery/fulls/05.jpg" class="image filtered span-3" data-position="top">
							<img src="images/gallery/thumbs/05.jpg" alt="" />
						</a>
						<a href="images/gallery/fulls/06.jpg" class="image filtered span-1-5" data-position="center">
							<img src="images/gallery/thumbs/06.jpg" alt="" />
						</a>
						<a href="images/gallery/fulls/07.jpg" class="image filtered span-1-5" data-position="bottom">
							<img src="images/gallery/thumbs/07.jpg" alt="" />
						</a>
						<a href="images/gallery/fulls/08.jpg" class="image filtered span-3" data-position="top">
							<img src="images/gallery/thumbs/08.jpg" alt="" />
						</a>
					</div>
					<a href="images/gallery/fulls/09.jpg" class="image filtered span-2-5" data-position="right">
						<img src="images/gallery/thumbs/09.jpg" alt="" />
					</a>
				</div>
			</section>

			<div class="copyrights">Collect from
				<a href="http://www.cssmoban.com/">手机网站模板</a>
			</div>

			<!-- Panel -->
			<section class="panel color2-alt">
				<div class="intro color2">
					<h2 class="major">感谢</h2>
					<p> 放飞一只白鸽给你，捎上我的思念，捎上我的祝福，飘向你的心海，飘向你的生活，愿你快快乐乐地面对每个晨钟暮鼓，高高兴兴地面对花开花落。</p>
				</div>
			</section>

			<!-- Copyright -->
			<div class="copyright">&copy; Untitled. Design:
				<a href="https://html5up.net">HTML5 UP</a>.</div>

		</div>

	</div>
{% endblock body %}

templates/users/user_login.html
{% extends 'common/base.html' %}

{% load staticfiles %}

{% block title %}
	<title>花匠铺-用户登录</title>
{% endblock %}

{% block body %}
	<!-- Page Wrapper -->
	<div id="page-wrapper">

		<!-- Wrapper -->
		<div id="wrapper">

			<!-- Panel -->
			<section class="panel color2-alt">
				<div class="intro color2">
					<h2 class="major">登录</h2>
					<p>欢迎您回来</p>
                    <br>
                    还没有账号<a href="{% url 'users:register' %}"><strong>去注册</strong></a>
				</div>
				<div class="inner columns aligned">
					<div class="span-4-5">
						<h3 class="major">请登录</h3>
						<form method="post" action="{% url 'users:login_handle' %}">
							{% csrf_token %}
                            <div class="field half" id="user_login">
								<label for="u_name">姓名</label>
								<input type="text" name="u_name" id="u_name" placeholder="用户名" />
							</div>
							<div class="field half" id="user_login_pwd">
								<label for="u_pass">密码</label>
								<input type="text" name="u_pass" id="u_pass" placeholder="密码" />
							</div>

							<div class="field third" id="phone_login">
								<input type="text" id="user_phone" placeholder="请输入您的手机号码" />
							</div>
							<div class="field quarter" id="phone_login_btn">
								<input type="button" value="发送验证码" class="special color2" />
							</div>
							<div class="field" id="phone_login_code">
								<input type="email" id="user_code" value="" placeholder="验证码" />
							</div>


							<div class="field" id="login_method">
								<label for="demo-email">
									<a href="javascript:;">切换登录方式</a>
								</label>
							</div>

							<div class="field quarter">
								<input type="checkbox" id="demo-human" name="user_memb" class="color2" checked />
								<label for="demo-human">记住用户名</label>
							</div>
							<ul class="actions field">
								<li>
									<input type="submit" value="提交" class="special color2" />
								</li>
							</ul>
						</form>
					</div>
			</section>

			<!-- Copyright -->
			<div class="copyright">&copy; 安徽省黄山市歙县:
				<a href="https://html5up.net">花匠铺</a>.</div>

			</div>

		</div>

{% endblock body %}

{% block footer_js %}
    <script>
			$(function () {
				$('#phone_login, #phone_login_btn, #phone_login_code').hide();
				$('#login_method').click(function () {
					login_mothed_change()
				});

				function login_mothed_change() {
					if ($("#phone_login").is(":hidden")) {
						$('#phone_login, #phone_login_btn, #phone_login_code').show();
						$('#user_login, #user_login_pwd').hide();
					} else {
						$('#phone_login, #phone_login_btn, #phone_login_code').hide();
						$('#user_login, #user_login_pwd').show();
					}
				}
			})
		</script>
{% endblock footer_js %}

templates/users/user_order.html
{% extends 'common/base.html' %}

{% load staticfiles %}

{% block title %}
	<title>花匠铺-个人主页</title>
{% endblock title %}

{% block body %}
	<!-- Page Wrapper -->
	<div id="page-wrapper">

		<!-- Wrapper -->
		<div id="wrapper">

			<!-- Panel (Banner) -->
			<section class="panel banner right">
				<div class="content color0 span-2-75">
					<h1 class="major">欢迎回来！
						<br /> 张三丰
					</h1>
					<p>今天你的幸运花是
						<strong>紫罗兰</strong>,代表永恒的美丽
						<br>
						<a href="#" target="_blank" title="查看订单">查看订单</a>
						<br>
						<a href="#" target="_blank" title="修改地址">修改地址</a>
					</p>
				</div>
				<div class="image filtered span-2-75" data-position="25% 25%">
					<img src="images/user.jpg" alt="" />
				</div>
			</section>

			<!-- Panel -->
			<section class="panel color2-alt">
				<div class="intro color1">
					<h2 class="major">订单 》》</h2>
					<p>
						《迎春花》
						<br> 好一朵迎春花人人都爱它
						<br> 好一朵迎春花迎来大地放光华 </p>
				</div>
				<div class="inner columns aligned">
					<div class="span-3">
						<h3 class="major">订单号：193849384</h3>
						<h4>2017/2/1 12:30:41</h4>
						<div class="table-wrapper">
							<table>
								<thead>
									<tr>
										<th>名称</th>
										<th>数量</th>
										<th>单价</th>
										<th>总价</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>木兰花</td>
										<td>4</td>
										<td>1.99</td>
										<td>7.96</td>
									</tr>
									<tr>
										<td>大叶兰</td>
										<td>2</td>
										<td>3.99</td>
										<td>7.98</td>
									</tr>
									<tr>
										<td>玫瑰</td>
										<td>1</td>
										<td>9.99</td>
										<td>9.99</td>
									</tr>
								</tbody>
								<tfoot>
									<tr>
										<td colspan="3">
											<a href="#" class="button">现在去支付</a>
										</td>
										<td>25.93</td>
									</tr>
								</tfoot>
							</table>
						</div>
					</div>
				</div>
			</section>

			<!-- Panel -->
			<section class="panel color1-alt">
				<div class="inner columns aligned">
					<div class="span-3">
						<h3 class="major">订单号：193849384</h3>
						<h4>2017/2/1 12:30:41</h4>
						<div class="table-wrapper">
							<table>
								<thead>
									<tr>
										<th>名称</th>
										<th>数量</th>
										<th>单价</th>
										<th>总价</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>木兰花</td>
										<td>4</td>
										<td>1.99</td>
										<td>7.96</td>
									</tr>
									<tr>
										<td>大叶兰</td>
										<td>2</td>
										<td>3.99</td>
										<td>7.98</td>
									</tr>
									<tr>
										<td>玫瑰</td>
										<td>1</td>
										<td>9.99</td>
										<td>9.99</td>
									</tr>
								</tbody>
								<tfoot>
									<tr>
										<td colspan="3">
											<a href="#" class="button">现在去支付</a>
										</td>
										<td>25.93</td>
									</tr>
								</tfoot>
							</table>
						</div>
					</div>
				</div>
			</section>Í

			<!-- Panel -->
			<section class="panel">
				<div class="intro color2">
					<h2 class="major">人气商品</h2>
					<p> 看不清楚前面的道路，挽留不住岁月的脚步，还好有你的呵护，能听我把苦乐倾诉。感谢你，我的朋友，真心愿你好运一路，快乐常驻，把幸福一直留住。</p>
				</div>
				<div class="gallery">
					<div class="group span-3">
						<a href="images/gallery/fulls/01.jpg" class="image filtered span-3" data-position="bottom">
							<img src="images/gallery/thumbs/01.jpg" alt="" />
						</a>
						<a href="images/gallery/fulls/02.jpg" class="image filtered span-1-5" data-position="center">
							<img src="images/gallery/thumbs/02.jpg" alt="" />
						</a>
						<a href="images/gallery/fulls/03.jpg" class="image filtered span-1-5" data-position="bottom">
							<img src="images/gallery/thumbs/03.jpg" alt="" />
						</a>
					</div>
					<a href="images/gallery/fulls/04.jpg" class="image filtered span-2-5" data-position="top">
						<img src="images/gallery/thumbs/04.jpg" alt="" />
					</a>
					<div class="group span-4-5">
						<a href="images/gallery/fulls/05.jpg" class="image filtered span-3" data-position="top">
							<img src="images/gallery/thumbs/05.jpg" alt="" />
						</a>
						<a href="images/gallery/fulls/06.jpg" class="image filtered span-1-5" data-position="center">
							<img src="images/gallery/thumbs/06.jpg" alt="" />
						</a>
						<a href="images/gallery/fulls/07.jpg" class="image filtered span-1-5" data-position="bottom">
							<img src="images/gallery/thumbs/07.jpg" alt="" />
						</a>
						<a href="images/gallery/fulls/08.jpg" class="image filtered span-3" data-position="top">
							<img src="images/gallery/thumbs/08.jpg" alt="" />
						</a>
					</div>
					<a href="images/gallery/fulls/09.jpg" class="image filtered span-2-5" data-position="right">
						<img src="images/gallery/thumbs/09.jpg" alt="" />
					</a>
				</div>
			</section>

			<div class="copyrights">Collect from
				<a href="http://www.cssmoban.com/">手机网站模板</a>
			</div>

			<!-- Panel -->
			<section class="panel color2-alt">
				<div class="intro color2">
					<h2 class="major">感谢</h2>
					<p> 放飞一只白鸽给你，捎上我的思念，捎上我的祝福，飘向你的心海，飘向你的生活，愿你快快乐乐地面对每个晨钟暮鼓，高高兴兴地面对花开花落。</p>
				</div>
			</section>

			<!-- Copyright -->
			<div class="copyright">&copy; Untitled. Design:
				<a href="https://html5up.net">HTML5 UP</a>.</div>

		</div>

	</div>

{% endblock body %}

templates/users/user_register.html
{% extends 'common/base.html' %}

{% load staticfiles %}

{% block title %}
	<title>花匠铺-用户注册</title>
{% endblock %}

{% block body %}
	<!-- Page Wrapper -->
	<div id="page-wrapper">

		<!-- Wrapper -->
		<div id="wrapper">

			<!-- Panel -->
			<section class="panel color2-alt">
				<div class="intro color2">
					<h2 class="major">注册</h2>
					<p>感谢您对花匠铺的
						<br> 信任
					</p>
				</div>
				<div class="inner columns aligned">
					<div class="span-4-5">
						<h3 class="major">请填写您的个人信息</h3>
						<form method="post" action="{% url 'users:register_handle' %}">
							{% csrf_token %}
                            <div class="field half">
								<label for="u_name">姓名</label>
								<input type="text" name="u_name" id="u_name" placeholder="5-20个字符" />
							</div>
							<div class="field half">
								<label for="u_phone">手机号</label>
								<input type="text" name="u_phone" id="u_phone" placeholder="11个数字" />
							</div>

							<div class="field half">
								<label for="u_pass">请输入密码</label>
								<input type="password" name="u_pass" id="u_pass" placeholder="8-20个字符" />
							</div>
							<div class="field half">
								<label for="u_repass">请再次输入密码</label>
								<input type="password" name="u_repass" id="u_repass" placeholder="8-20个字符" />
							</div>

							<div class="field quarter">
								<input type="checkbox" id="user_protocol" name="user_protocol" class="color2" checked />
								<label for="user_protocol">同意用户协议</label>
							</div>
							<div class="field quarter">
									<a href="#">用户协议</a>
							</div>
							<ul class="actions field">
								<li>
									<input type="submit" value="提交" class="special color2" />
								</li>
							</ul>
						</form>
					</div>
				</div>
			</section>

			<!-- Copyright -->
			<div class="copyright">&copy; 安徽省黄山市歙县:
				<a href="https://html5up.net">花匠铺</a>.</div>
		</div>
	</div>

{% endblock body %}